ControleEstoque/ControleEstoque.Web/Controllers/Cadastro/CadCidadeController.cs
using ControleEstoque.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace ControleEstoque.Web.Controllers
{
    //[Authorize(Roles = "Gerente, Coordenador, Analista")]
    [Authorize]
    public class CadCidadeController : Controller
    {
        private const int _quantMaxLinhasPorPagina = 5;

        public ActionResult Index()
        {
            ViewBag.ListaTamPag = new SelectList(new int[] { _quantMaxLinhasPorPagina, 10, 15, 20 }, _quantMaxLinhasPorPagina);
            ViewBag.QuantMaxLinhasPorPagina = _quantMaxLinhasPorPagina;
            ViewBag.PaginaAtual = 1;

            var lista = CidadeModel.RecuperarLista(ViewBag.PaginaAtual, _quantMaxLinhasPorPagina);
            var quant = CidadeModel.RecuperarQuantidade();

            var difQuantPaginas = (quant % ViewBag.QuantMaxLinhasPorPagina) > 0 ? 1 : 0;
            ViewBag.QuantPaginas = (quant / ViewBag.QuantMaxLinhasPorPagina) + difQuantPaginas;
            ViewBag.Paises = PaisModel.RecuperarLista();

            return View(lista);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult CidadePagina(int pagina, int tamPag, string filtro, string ordem)
        {
            var lista = CidadeModel.RecuperarLista(pagina, tamPag, filtro, ordem: ordem);

            return Json(lista);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult RecuperarCidade(int id)
        {
            return Json(CidadeModel.RecuperarPeloId(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult RecuperarCidadesDoEstado(int idEstado)
        {
            var lista = CidadeModel.RecuperarLista(idEstado: idEstado);

            return Json(lista);
        }

        [HttpPost]
        [Authorize(Roles = "Gerente,Administrativo")]
        [ValidateAntiForgeryToken]
        public JsonResult ExcluirCidade(int id)
        {
            return Json(CidadeModel.ExcluirPeloId(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult SalvarCidade(CidadeModel model)
        {
            var resultado = "OK";
            var mensagens = new List<string>();
            var idSalvo = string.Empty;

            if (!ModelState.IsValid)
            {
                resultado = "AVISO";
                mensagens = ModelState.Values.SelectMany(x => x.Errors).Select(x => x.ErrorMessage).ToList();
            }
            else
            {
                try
                {
                    var id = model.Salvar();
                    if (id > 0)
                    {
                        idSalvo = id.ToString();
                    }
                    else
                    {
                        resultado = "ERRO";
                    }
                }
                catch (Exception ex)
                {
                    resultado = "ERRO";
                }
            }

            return Json(new { Resultado = resultado, Mensagens = mensagens, IdSalvo = idSalvo });
        }
    }
}

ControleEstoque/ControleEstoque.Web/Controllers/Cadastro/CadEstadoController.cs
using ControleEstoque.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace ControleEstoque.Web.Controllers
{
    //[Authorize(Roles = "Gerente,Administrativo,Operador")]
    [Authorize]
    public class CadEstadoController : Controller
    {
        private const int _quantMaxLinhasPorPagina = 5;

        public ActionResult Index()
        {
            ViewBag.ListaTamPag = new SelectList(new int[] { _quantMaxLinhasPorPagina, 10, 15, 20 }, _quantMaxLinhasPorPagina);
            ViewBag.QuantMaxLinhasPorPagina = _quantMaxLinhasPorPagina;
            ViewBag.PaginaAtual = 1;

            var lista = EstadoModel.RecuperarLista(ViewBag.PaginaAtual, _quantMaxLinhasPorPagina);
            var quant = EstadoModel.RecuperarQuantidade();

            var difQuantPaginas = (quant % ViewBag.QuantMaxLinhasPorPagina) > 0 ? 1 : 0;
            ViewBag.QuantPaginas = (quant / ViewBag.QuantMaxLinhasPorPagina) + difQuantPaginas;
            ViewBag.Paises = PaisModel.RecuperarLista();

            return View(lista);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public JsonResult EstadoPagina(int pagina, int tamPag, string filtro, string ordem)
        {
            var lista = EstadoModel.RecuperarLista(pagina, tamPag, filtro, ordem: ordem);

            return Json(lista);
        }
        
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public JsonResult RecuperarEstadosDoPais(int idPais)
        {
            var lista = EstadoModel.RecuperarLista(idPais: idPais);

            return Json(lista);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public JsonResult RecuperarEstado(int id)
        {
            return Json(EstadoModel.RecuperarPeloId(id));
        }

        [HttpPost]
        //[Authorize(Roles = "Gerente,Administrativo")]
        [Authorize]
        [ValidateAntiForgeryToken]
        public JsonResult ExcluirEstado(int id)
        {
            return Json(EstadoModel.ExcluirPeloId(id));
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public JsonResult SalvarEstado(EstadoModel model)
        {
            var resultado = "OK";
            var mensagens = new List<string>();
            var idSalvo = string.Empty;

            if (!ModelState.IsValid)
            {
                resultado = "AVISO";
                mensagens = ModelState.Values.SelectMany(x => x.Errors).Select(x => x.ErrorMessage).ToList();
            }
            else
            {
                try
                {
                    var id = model.Salvar();
                    if (id > 0)
                    {
                        idSalvo = id.ToString();
                    }
                    else
                    {
                        resultado = "ERRO";
                    }
                }
                catch (Exception ex)
                {
                    resultado = "ERRO";
                }
            }

            return Json(new { Resultado = resultado, Mensagens = mensagens, IdSalvo = idSalvo });
        }
    }
}

ControleEstoque/ControleEstoque.Web/Controllers/Cadastro/CadFornecedorController.cs
using ControleEstoque.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ControleEstoque.Web.Controllers
{
    //[Authorize(Roles ="Gerente,Administrativo,Operador")]
    [Authorize]
    public class CadFornecedorController : Controller
    {
        private const int _quantMaxLinhasPorPagina = 5;

        public ActionResult Index()
        {
            ViewBag.ListaTamPag = new SelectList(new int[] { _quantMaxLinhasPorPagina, 10, 15, 20 }, _quantMaxLinhasPorPagina);
            ViewBag.QuantMaxLinhasPorPagina = _quantMaxLinhasPorPagina;
            ViewBag.PaginaAtual = 1;

            var lista = FornecedorModel.RecuperarLista(ViewBag.PaginaAtual, _quantMaxLinhasPorPagina);
            var quant = FornecedorModel.RecuperarQuantidade();

            var difQuantPaginas = (quant % ViewBag.QuantMaxLinhasPorPagina) > 0 ? 1 : 0;
            ViewBag.QuantPaginas = (quant / ViewBag.QuantMaxLinhasPorPagina) + difQuantPaginas;
            ViewBag.Paises = PaisModel.RecuperarLista();

            return View(lista);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public JsonResult FornecedorPagina(int pagina, int tamPag, string filtro, string ordem)
        {
            var lista = FornecedorModel.RecuperarLista(pagina, tamPag, filtro, ordem: ordem);

            return Json(lista);
        }       

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public JsonResult RecuperarFornecedor(int id)
        {
            return Json(FornecedorModel.RecuperarPeloId(id));
        }

        [HttpPost]
        [Authorize]
        //[Authorize(Roles = "Gerente,Administrativo")]
        [ValidateAntiForgeryToken]
        public JsonResult ExcluirFornecedor(int id)
        {
            return Json(FornecedorModel.ExcluirPeloId(id));
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public JsonResult SalvarFornecedor(FornecedorModel model)
        {
            var resultado = "OK";
            var mensagens = new List<string>();
            var idSalvo = string.Empty;

            if (!ModelState.IsValid)
            {
                resultado = "AVISO";
                mensagens = ModelState.Values.SelectMany(x => x.Errors).Select(x => x.ErrorMessage).ToList();
            }
            else
            {
                try
                {
                    var id = model.Salvar();
                    if (id > 0)
                    {
                        idSalvo = id.ToString();
                    }
                    else
                    {
                        resultado = "ERRO";
                    }
                }
                catch (Exception ex)
                {
                    resultado = "ERRO";
                }
            }

            return Json(new { Resultado = resultado, Mensagens = mensagens, IdSalvo = idSalvo });
        }
    }
}

ControleEstoque/ControleEstoque.Web/Controllers/Cadastro/CadGrupoProdutoController.cs
using ControleEstoque.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ControleEstoque.Web.Controllers
{
    [Authorize]
    public class CadGrupoProdutoController : Controller
    {
        private const int _quantMaxLinhasPorPagina = 5;

        public ActionResult Index()
        {
            ViewBag.ListaTamPag = new SelectList(new int[] { _quantMaxLinhasPorPagina, 10, 15, 20 }, _quantMaxLinhasPorPagina);
            ViewBag.QuantMaxLinhasPorPagina = _quantMaxLinhasPorPagina;
            ViewBag.PaginaAtual = 1;

            var lista = GrupoProdutoModel.RecuperarLista(ViewBag.PaginaAtual, _quantMaxLinhasPorPagina);
            var quant = GrupoProdutoModel.RecuperarQuantidade();

            var difQuantPaginas = (quant % ViewBag.QuantMaxLinhasPorPagina) > 0 ? 1 : 0;
            ViewBag.QuantPaginas = (quant / ViewBag.QuantMaxLinhasPorPagina) + difQuantPaginas;

            return View(lista);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public JsonResult GrupoProdutoPagina(int pagina, int tamPag, string filtro, string ordem)
        {
            var lista = GrupoProdutoModel.RecuperarLista(pagina, tamPag, filtro, ordem: ordem);

            return Json(lista);
        }
            
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public JsonResult RecuperarGrupoProduto(int id)
        {
            return Json(GrupoProdutoModel.RecuperarPeloId(id));
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public JsonResult ExcluirGrupoProduto(int id)
        {
            return Json(GrupoProdutoModel.ExcluirPeloId(id));
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public JsonResult SalvarGrupoProduto(GrupoProdutoModel model)
        {
            var resultado = "OK";
            var mensagens = new List<string>();
            var idSalvo = string.Empty;

            if (!ModelState.IsValid)
            {
                resultado = "AVISO";
                mensagens = ModelState.Values.SelectMany(x => x.Errors).Select(x => x.ErrorMessage).ToList();
            }
            else
            {
                try
                {
                    var id = model.Salvar();
                    if (id > 0)
                    {
                        idSalvo = id.ToString();
                    }
                    else
                    {
                        resultado = "ERRO";
                    }
                }
                catch (Exception ex)
                {
                    resultado = "ERRO";
                }
            }

            return Json(new { Resultado = resultado, Mensagens = mensagens, IdSalvo = idSalvo });
        }
    }
}

ControleEstoque/ControleEstoque.Web/Controllers/Cadastro/CadLocalArmazenamentoController.cs
using ControleEstoque.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace ControleEstoque.Web.Controllers
{
    [Authorize]
    public class CadLocalArmazenamentoController : Controller
    {
        private const int _quantMaxLinhasPorPagina = 5;

        public ActionResult Index()
        {
            ViewBag.ListaTamPag = new SelectList(new int[] { _quantMaxLinhasPorPagina, 10, 15, 20 }, _quantMaxLinhasPorPagina);
            ViewBag.QuantMaxLinhasPorPagina = _quantMaxLinhasPorPagina;
            ViewBag.PaginaAtual = 1;

            var lista = LocalArmazenamentoModel.RecuperarLista(ViewBag.PaginaAtual, _quantMaxLinhasPorPagina);
            var quant = LocalArmazenamentoModel.RecuperarQuantidade();

            var difQuantPaginas = (quant % ViewBag.QuantMaxLinhasPorPagina) > 0 ? 1 : 0;
            ViewBag.QuantPaginas = (quant / ViewBag.QuantMaxLinhasPorPagina) + difQuantPaginas;

            return View(lista);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public JsonResult LocalArmazenamentoPagina(int pagina, int tamPag, string filtro, string ordem)
        {
            var lista = LocalArmazenamentoModel.RecuperarLista(pagina, tamPag, filtro, ordem: ordem);

            return Json(lista);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public JsonResult RecuperarLocalArmazenamento(int id)
        {
            return Json(LocalArmazenamentoModel.RecuperarPeloId(id));
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public JsonResult ExcluirLocalArmazenamento(int id)
        {
            return Json(LocalArmazenamentoModel.ExcluirPeloId(id));
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public JsonResult SalvarLocalArmazenamento(LocalArmazenamentoModel model)
        {
            var resultado = "OK";
            var mensagens = new List<string>();
            var idSalvo = string.Empty;

            if (!ModelState.IsValid)
            {
                resultado = "AVISO";
                mensagens = ModelState.Values.SelectMany(x => x.Errors).Select(x => x.ErrorMessage).ToList();
            }
            else
            {
                try
                {
                    var id = model.Salvar();
                    if (id > 0)
                    {
                        idSalvo = id.ToString();
                    }
                    else
                    {
                        resultado = "ERRO";
                    }
                }
                catch (Exception ex)
                {
                    resultado = "ERRO";
                }
            }

            return Json(new { Resultado = resultado, Mensagens = mensagens, IdSalvo = idSalvo });
        }
    }
}

ControleEstoque/ControleEstoque.Web/Controllers/GraficoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ControleEstoque.Web.Controllers
{
    public class GraficoController : Controller
    {
        [Authorize]
        public ActionResult PerdaMes()
        {
            return View();
        }

        [Authorize]
        public ActionResult EntradaSaidaMes()
        {
            return View();
        }

        [Authorize]
        public ActionResult ColetasPorMes()
        {
            return View();
        }
    }
}

ControleEstoque/ControleEstoque.Web/Controllers/OperacaoController.cs
using System.Web.Mvc;

namespace ControleEstoque.Web.Controllers
{
    public class OperacaoController : Controller
    {                
        [Authorize]
        public ActionResult LancPerdaProduto()
        {
            return View();
        }       
    }
}

ControleEstoque/ControleEstoque.Web/Controllers/RelatorioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ControleEstoque.Web.Controllers
{
    public class RelatorioController : Controller
    {
        [Authorize]
        public ActionResult PosicaoEstoque()
        {
            return View();
        }

        [Authorize]
        public ActionResult Ressuprimento()
        {
            return View();
        }

        [Authorize]
        public ActionResult ControleOperacional()
        {
            return View();
        }

    }
}

ControleEstoque/ControleEstoque.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - About - Inventory Control - Training with by Ranieri Silva.</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/sweetalert2.min.css" rel="stylesheet" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <img src="~/img/home/home_1.ico" style="width:10%; margin: 10px"/>
                @Html.ActionLink("Controle de Estoque", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                @* - Vamos restringir acesso somente Se (If) estiverem logados... Usando "Request.IsAuthenticated" *@
                @if (Request.IsAuthenticated)
                {
                    <ul class="nav navbar-nav">
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="color: yellow">
                                Cadastros
                                <span class="caret" style="color: dodgerblue"></span>
                            </a>
                            <ul class="dropdown-menu" style="background-color: lightskyblue";>
                                @*ABAIXO TEMOS: O LINK DO TEXTO - O NOME DA ACTION E O CONTROLLER *@
                                <li>@Html.ActionLink("Grupo de Produtos", "Index", "CadGrupoProduto")</li>
                                <li>@Html.ActionLink("Marcas de Produtos", "Index", "CadMarcaProduto")</li>
                                <li>@Html.ActionLink("Locais de Armazenamento", "Index", "CadLocalArmazenamento")</li>
                                <li>@Html.ActionLink("Unidades de Medidas", "Index", "CadUnidadeMedida")</li>
                                <li>@Html.ActionLink("Produtos", "Index", "CadProduto")</li>
                                <li class="nav-divider" style="border: groove"></li>
                                <li>@Html.ActionLink("Paises", "Index", "CadPais")</li>
                                <li>@Html.ActionLink("Estados", "Index", "CadEstado")</li>
                                <li>@Html.ActionLink("Cidades", "Index", "CadCidade")</li>
                                <li>@Html.ActionLink("Fornecedores", "Index", "CadFornecedor")</li>
                                <li class="nav-divider" style="border: groove"></li>
                                <li>@Html.ActionLink("Perfis de Usuários", "Index", "CadPerfil")</li>
                                <li>@Html.ActionLink("Usuários", "Index", "CadUsuario")</li>
                            </ul>
                        </li>
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="color: yellow">
                                Operações
                                <span class="caret" style="color: dodgerblue"></span>
                            </a>
                            <ul class="dropdown-menu" style="background-color: lightskyblue";>
                                @*ABAIXO TEMOS: O LINK DO TEXTO - O NOME DA ACTION E O CONTROLLER *@
                                <li>@Html.ActionLink("Entrada de Produtos", "Index", "OperEntradaProduto")</li>
                                <li>@Html.ActionLink("Saída de Produtos", "Index", "OperSaidaProduto")</li>
                                <li class="nav-divider" style="border: groove"></li>
                                <li>@Html.ActionLink("Lançamento de Perdas de Produtos", "LancPerdaProduto", "Operacao")</li>
                                <li>@Html.ActionLink("Inventário de Estoque", "Index", "OperInventario")</li>
                            </ul>
                        </li>
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="color: yellow">
                                Relatórios
                                <span class="caret" style="color: dodgerblue"></span>
                            </a>
                            <ul class="dropdown-menu" style="background-color: lightskyblue" ;>
                                @*ABAIXO TEMOS: O LINK DO TEXTO - O NOME DA ACTION E O CONTROLLER *@
                                <li>@Html.ActionLink("Posição de Estoque", "PosicaoEstoque", "Relatorio")</li>
                                <li class="nav-divider" style="border: groove"></li>
                                <li>@Html.ActionLink("Ressuprimento", "Ressuprimento", "Relatorio")</li>
                                <li class="nav-divider" style="border: groove"></li>
                                <li>@Html.ActionLink("Controle Operacional", "ControleOperacional", "Relatorio")</li>
                            </ul>
                        </li>
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="color: yellow">
                                Gráficos
                                <span class="caret" style="color: dodgerblue"></span>
                            </a>
                            <ul class="dropdown-menu" style="background-color: lightskyblue" ;>
                                @*ABAIXO TEMOS: O NOME DO TEXTO - OS CONTROLLERS - E AS VIEWS*@
                                <li>@Html.ActionLink("Perda por Mês", "PerdaMes", "Grafico")</li>
                                <li class="nav-divider" style="border: groove"></li>
                                <li>@Html.ActionLink("Entrada versos Saída por mês", "EntradaSaidaMes", "Grafico")</li>
                                <li class="nav-divider" style="border: groove"></li>
                                <li>@Html.ActionLink("Coletas por mês", "ColetasPorMes", "Grafico")</li>
                            </ul>
                        </li>
                    </ul>
                    @* - ABAIXO Temos o Elemento Form Html para o nome da Action "logOff" e o Controller "Conta" *@
                    using (Html.BeginForm("logOff", "Conta", FormMethod.Post, new { id = "logoffForm" }))
                    {
                        <ul class="nav navbar-nav navbar-right">
                            @*ABAIXO TEMOS: O LINK DO TEXTO - O NOME DA ACTION E O CONTROLLER *@
                            <li>@Html.ActionLink("Sobre", "Sobre", "Home")</li>
                            <li>
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="color: deepskyblue">
                                    Olá! - @User.Identity.Name
                                    <span class="caret" style="color: dodgerblue"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("Alteração de Senha", "AlterarSenhaUsuario", "Conta")</li>
                                </ul>
                            </li>
                            <li>
                                <a href="javascript: document.getElementById('logoffForm').submit()">
                                    <span>
                                        <img src="~/img/_layoutSair/sair.ico" alt="ícone sair" style="width:45%" /> Sair
                                    </span>
                                </a>
                            </li>
                        </ul>
                    }
                }
                else
                {
                    <ul class="nav navbar-nav navbar-right">
                        @*ABAIXO TEMOS: O NOME DO TEXTO - OS CONTROLLERS - E AS VIEWS*@
                        <li>@Html.ActionLink("Login", "Login", "Conta")</li>
                    </ul>
                }

            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />

        @if (Request.IsAuthenticated)
        {
            <footer>
                <p>&copy; @DateTime.Now.Year - Controle de Estoque -<spam style="color: red"> By @User.Identity.Name</spam></p>
            </footer>
        }
        else
        {
            <footer>
                <div class="rowimgfooter">
                    <div class="col-md-3 col-md-offset-5">
                        <img src="~/img/footer/callcenter.ico" alt="CallCenter no Footer" style="width:90%" />
                    </div>
                    <div class="col-md-9 col-md-offset-3">
                        <p>&copy; @DateTime.Now.Year - <spam style="color: red"> 0800-15775-100 </spam></p>
                    </div>
                </div>
            </footer>
        }

    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/sweetalert2.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>